#Estrategia de manejo de BBDD
spring.jpa.hibernate.ddl-auto=update
#Direccion base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/backendarb?useSSL=false&serverTimezone=UTC
#Datos para acceder a la base de datos
spring.datasource.username=root
spring.datasource.password=
#Version de la vase de datos
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#JWT
jwt.secret = secret
# El numero es cuanto dura el token en milisegundos
jwt.expiration = 7200